apiVersion: v1
kind: Secret
metadata:
  name: loki-minio-credentials
  namespace: logging
type: Opaque
stringData:
  LOKI_S3_ACCESS_KEY_ID: "<LOKI_MINIO_ACCESS_KEY>"
  LOKI_S3_SECRET_ACCESS_KEY: "<LOKI_MINIO_SECRET_KEY>"

